name: 🐛 不具合＆バグ
description: Create a bug report.
title: "🐛[Bug]: "
labels: ["bug", "🐛 Bug"]
body:
  - type: checkboxes
    id: bug-type
    attributes:
      label: 何に関する不具合＆バグ？
      options:
        - label: 見た目
        - label: 動作
        - label: ロジック
        - label: 環境
  - type: checkboxes
    id: os
    attributes:
      label: OS
      options:
        - label: Windows
        - label: Mac
        - label: Linux
        - label: iOS
        - label: Android
        - label: その他
  - type: checkboxes
    id: browser
    attributes:
      label: ブラウザ
      options:
        - label: Chrome
        - label: Safari
        - label: FireFox
        - label: Edge
        - label: その他
  - type: textarea
    id: what-happened
    attributes:
      label: 何が起きてる？（再現方法など詳しく）
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: エラーログがあればコピペして！
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: how-to-fix
    attributes:
      label: 修正方法の提案
