name: 不具合＆バグ
description: Create a bug report.
title: "🐛[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    id: type
    attributes:
      label: 何に関すること？（複数選択可能）
      options:
        - 見た目
        - 動作
        - ロジック
        - 環境
  - type: textarea
    id: what-happened
    attributes:
      label: 何が起きてる？
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: ブラウザは何？
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: エラーログがあればコピペして！
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
